### ISSUE TITLE
Feature: Create Todo App with Context API

### ISSUE THREAD

**Issue by jeffreyriosjr** [jeffreyriosjr/react-todo-context#1]
1. Build a single page todo application in plain react with a context api
2. Create Features:
- [ ] Input Component to pass in your todo
- [ ] List component that lists out your todos
- [ ] Check off todo item when completed
